version: '3'
services:
  node-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - database
      - redis
    environment:
      DB_HOST: database
      DEBUG: my-app:*
    env_file:
      - .env
    command: ["sh", "-c", "sleep 40 && npm start"]
    networks:
      - app-network

  database:
    build:
      context: ./src/db
    ports:
      - '3307:3306'
    hostname: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shortUrl
      MYSQL_USER: bogdan
      MYSQL_HOST: database
      MYSQL_PASSWORD: userpassword

    networks:
      - app-network
    env_file:
      - .env
      
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge